name: FTP Deploy to Subterra

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: extranet/notesdefrais/
          exclude: |
            assets/**
            .github/**
            LICENSE
            README.md
            .gitignore
            .vscode/**
            .DS_Store
            .git/**
