name: FTP Deploy to Subterra

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload to FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -c "set ftp:list-options -a; open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R --verbose \
            --exclude-glob .github/ \
            --exclude-glob .vscode/ \
            --exclude-glob .git/ \
            --exclude-glob .DS_Store \
            --exclude-glob LICENSE \
            --exclude-glob README.md \
            --exclude-glob .gitignore \
            ./ extranet/notesdefrais"
